### ISSUE TITLE
please add simplejson to requirements.txt

### ISSUE THREAD

**Issue by vincenzoml** [FizzleDorf/ComfyUI_FizzNodes#10]
As in subject :)

**Comment by FizzleDorf** [comment]
this has been done 4 months ago, you can check it out [here](https://github.com/FizzleDorf/ComfyUI_FizzNodes/blob/c27192e6f52c55afbf1dbdf58a9641f8a4c62344/requirements.txt#L3). If there is an issue related to installing simplejson through the requirements.txt, walk me through the process so I can try to replicate it otherwise close this issue.

**Comment by vincenzoml** [comment]
Oh, sorry, I assumed it was not there because I did pip install -r requirements.txt and afterwards, the simplejson package was missing. You can check this easily e.g. using a docker machine. Maybe because there's a missing newline at the end of requirements.txt?

**Comment by FizzleDorf** [comment]
> Maybe because there's a missing newline at the end of requirements.txt?

this was it. Thanks for the heads up. I've made an update (it doesn't actually show the newline in git but it's there. I pulled and checked)

**Comment by FizzleDorf** [comment]
I simply removed simplejson and just used the standard json module.

**Comment by vincenzoml** [comment]
Great!
