### ISSUE TITLE
Request: Full workflow screenshot or json

### ISSUE THREAD

**Issue by KewkLW** [FizzleDorf/ComfyUI_FizzNodes#9]
Would be very helpful if any working example workflows were added.

**Comment by FizzleDorf** [comment]
This is my next focus as I want to include as much guidance with notes as possible for an easy time using the nodes and best results.

**Comment by sesopenko** [comment]
I can possibly help out with some of the documentation.  I put a project together which is using BatchValueScheduleLatentInput and BatchPromptScheduleLatentInput, and can narrow it down to a simple example of the two.  It can also include an example of negative prompting mixed in with positive prompting, since `--neg` isn't documented in the readme yet.
